### ISSUE TITLE
conda install conflict

### ISSUE THREAD

**Issue by mfojtak** [QuantStack/xplot#23]
When installing xplot and xeus-cling using conda - the conflict is reported

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - xeus-cling
  - xplot
```

**Comment by JohanMabille** [comment]
Which version of conda are you using? I remember that 4.3.33 or 4.3.34 is broken, reverting to the previous one should fix your issue.

**Comment by SylvainCorlay** [comment]
We have pushed xplot 0.4.0 to the QuantStack channel. This should be fixed now.
